"""initial_migration

Revision ID: f6ce416e0f1f
Revises: 3a7e4068f8d7
Create Date: 2026-04-12 00:09:13.167706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ce416e0f1f'
down_revision: Union[str, Sequence[str], None] = '3a7e4068f8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_dates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('minute', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_d_dates_date'), 'd_dates', ['date'], unique=False)
    op.create_table('d_device_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('os', sa.String(), nullable=False),
    sa.Column('device_type', sa.String(), nullable=False),
    sa.Column('browser', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('os', 'device_type', 'browser', name='uix_os_device_type_browser')
    )
    op.create_table('d_event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('d_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'state', 'country', name='uq_city_state_country')
    )
    op.create_index(op.f('ix_d_locations_city'), 'd_locations', ['city'], unique=False)
    op.create_index(op.f('ix_d_locations_country'), 'd_locations', ['country'], unique=False)
    op.create_index(op.f('ix_d_locations_state'), 'd_locations', ['state'], unique=False)
    op.create_table('d_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('full_path', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_d_pages_full_path'), 'd_pages', ['full_path'], unique=False)
    op.create_index(op.f('ix_d_pages_host'), 'd_pages', ['host'], unique=False)
    op.create_index(op.f('ix_d_pages_page_name'), 'd_pages', ['page_name'], unique=False)
    op.create_index(op.f('ix_d_pages_url'), 'd_pages', ['url'], unique=False)
    op.create_table('d_referral_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('referrer_url', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('social', 'search', 'email', 'direct', 'other', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'referrer_url', 'category', name='uq_referral_source_url_category')
    )
    op.create_index(op.f('ix_d_referral_sources_referrer_url'), 'd_referral_sources', ['referrer_url'], unique=False)
    op.create_index(op.f('ix_d_referral_sources_source'), 'd_referral_sources', ['source'], unique=False)
    op.create_table('d_visitors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visitor_type', sa.Enum('new', 'returning', native_enum=False), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), nullable=True),
    sa.Column('account_status', sa.Enum('active', 'inactive', 'deleted', native_enum=False), nullable=False),
    sa.Column('portfolio_created_at', sa.DateTime(), nullable=True),
    sa.Column('user_type', sa.Enum('guest', 'user', 'admin', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_user_device')
    )
    op.create_index(op.f('ix_d_visitors_device_id'), 'd_visitors', ['device_id'], unique=False)
    op.create_index(op.f('ix_d_visitors_portfolio_created_at'), 'd_visitors', ['portfolio_created_at'], unique=False)
    op.create_index(op.f('ix_d_visitors_signup_date'), 'd_visitors', ['signup_date'], unique=False)
    op.create_index(op.f('ix_d_visitors_user_id'), 'd_visitors', ['user_id'], unique=False)
    op.create_table('f_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('referral_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.Column('properties', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['date_id'], ['d_dates.id'], ),
    sa.ForeignKeyConstraint(['device_type_id'], ['d_device_types.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['d_event_types.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['d_locations.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['d_pages.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['d_referral_sources.id'], ),
    sa.ForeignKeyConstraint(['visitor_id'], ['d_visitors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sharks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('sharktype', sa.TEXT(), nullable=False),
    sa.Column('length', sa.INTEGER(), nullable=False)
    )
    op.drop_table('f_events')
    op.drop_index(op.f('ix_d_visitors_user_id'), table_name='d_visitors')
    op.drop_index(op.f('ix_d_visitors_signup_date'), table_name='d_visitors')
    op.drop_index(op.f('ix_d_visitors_portfolio_created_at'), table_name='d_visitors')
    op.drop_index(op.f('ix_d_visitors_device_id'), table_name='d_visitors')
    op.drop_table('d_visitors')
    op.drop_index(op.f('ix_d_referral_sources_source'), table_name='d_referral_sources')
    op.drop_index(op.f('ix_d_referral_sources_referrer_url'), table_name='d_referral_sources')
    op.drop_table('d_referral_sources')
    op.drop_index(op.f('ix_d_pages_url'), table_name='d_pages')
    op.drop_index(op.f('ix_d_pages_page_name'), table_name='d_pages')
    op.drop_index(op.f('ix_d_pages_host'), table_name='d_pages')
    op.drop_index(op.f('ix_d_pages_full_path'), table_name='d_pages')
    op.drop_table('d_pages')
    op.drop_index(op.f('ix_d_locations_state'), table_name='d_locations')
    op.drop_index(op.f('ix_d_locations_country'), table_name='d_locations')
    op.drop_index(op.f('ix_d_locations_city'), table_name='d_locations')
    op.drop_table('d_locations')
    op.drop_table('d_event_types')
    op.drop_table('d_device_types')
    op.drop_index(op.f('ix_d_dates_date'), table_name='d_dates')
    op.drop_table('d_dates')
    # ### end Alembic commands ###
